name: Unit Tests

on: [push, pull_request]

# DuinoLed has no source files that are unottest-able
#
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install tools
      run: make TOP_DIR=. BOARD=pico install-tools

    - name: Run tools (test-style, lint, docs, unittest, coverage)
      run: make TOP_DIR=. BOARD=pico run-tools

    - name: Make sure all of the examples compile
      run: make TOP_DIR=. BOARD=pico compile-examples
