name: Unit Tests

on: [push, pull_request]

# DuinoLed has no source files that are unottest-able
#
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Check that the code is styled properly

    - name: Test Code Formatting
      run: make TOP_DIR=. BOARD=pico test-style

    # Run the linter

    - name: Install cpplint
      run: sudo apt install cpplint
      working-directory: .

    - name: Run Linter
      run: make TOP_DIR=. BOARD=pico lint

    # Check that everything is documented

    - name: Install doxygen
      run: sudo apt install doxygen graphviz
      working-directory: .

    - name: Test that docs passes
      run: make TOP_DIR=. BOARD=pico docs
